import { useAuth } from "@/_core/hooks/useAuth";
import { CaspaShell } from "@/components/CaspaShell";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { parseCaspaError } from "@/lib/caspaError";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, ShieldCheck, ThumbsDown } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation, useRoute } from "wouter";

export default function ApprovalInboxPage() {
  const { isAuthenticated, loading } = useAuth(); const [, params] = useRoute("/projects/:id/approvals"); const [, setLocation] = useLocation(); const projectId = Number(params?.id || 0); const utils = trpc.useUtils();
  const inbox = trpc.collaboration.approvalInbox.useQuery({ projectId }, { enabled: isAuthenticated && projectId > 0 }); const [notes, setNotes] = useState<Record<number, string>>({});
  const decide = trpc.collaboration.decide.useMutation({ onSuccess: async () => { toast.success("Your immutable decision is recorded."); await utils.collaboration.approvalInbox.invalidate({ projectId }); }, onError: error => toast.error(parseCaspaError(error, "Your decision could not be recorded.").message) });
  if (loading || inbox.isLoading) return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="size-7 animate-spin text-primary" /></div>;
  if (!isAuthenticated) { setLocation("/"); return null; }
  if (!inbox.data) return <CaspaShell><div className="container flex min-h-[calc(100vh-80px)] max-w-3xl items-center py-10"><section className="literary-card relative w-full overflow-hidden p-8 text-center sm:p-10"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary to-transparent" /><ShieldCheck className="mx-auto size-7 text-primary" /><p className="mt-6 eyebrow">Approval desk</p><h1 className="mt-2 text-4xl font-semibold">No collaborator access here.</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-muted-foreground">Approval desks belong to active invited editors and designers. Authors configure review gates from the collaboration desk; collaborators join with a private code and then see only the decisions assigned to their role.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={() => setLocation("/join")}>Join with invitation code</Button><Button variant="outline" onClick={() => setLocation("/")}>Return to writing desk</Button></div></section></div></CaspaShell>;
  return <CaspaShell><div className="container py-10"><section className="literary-card p-6 sm:p-8"><p className="eyebrow">{inbox.data.role} approval desk</p><h1 className="mt-2 text-5xl font-semibold">{inbox.data.projectTitle}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Your decision is recorded once and becomes visible in the author’s audit history. It never replaces author approval.</p><div className="mt-7 space-y-4">{inbox.data.items.length ? inbox.data.items.map(item => <div key={`${item.targetType}-${item.targetId}`} className="rounded-xl border border-border bg-black/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">{item.area.replace(/-/g, " ")}</p><h2 className="mt-1 text-2xl font-semibold">{item.title}</h2><p className="mt-2 text-sm text-muted-foreground">{item.detail}</p></div><ShieldCheck className="size-5 text-primary" /></div><Textarea value={notes[item.targetId] || ""} onChange={event => setNotes(current => ({ ...current, [item.targetId]: event.target.value }))} className="mt-4 min-h-24 bg-black/15" placeholder="Optional approval note" /><div className="mt-4 flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={decide.isPending} onClick={() => decide.mutate({ projectId, area: item.area, targetType: item.targetType, targetId: item.targetId, decision: "rejected", note: notes[item.targetId] || undefined })}><ThumbsDown className="size-4" /> Record rejection</Button><Button disabled={decide.isPending} onClick={() => decide.mutate({ projectId, area: item.area, targetType: item.targetType, targetId: item.targetId, decision: "approved", note: notes[item.targetId] || undefined })}><Check className="size-4" /> Record approval</Button></div></div>) : <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No configured decisions are waiting for your role.</div>}</div></section></div></CaspaShell>;
}
